{{- if .Values.dois.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: flow-devopsinsight
  labels:
    app: flow-devopsinsight
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  clusterIP: "None"
  ports:
    - name: servicep1-dois
      port: 9200
      targetPort: p1-dois
      protocol: TCP
  selector:
    app: flow-devopsinsight
    release: {{ .Release.Name }}
{{- end }}

