{{- if .Values.dois.enabled -}}
{{- if not .Values.dois.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cloudbees-flow.fullname" . }}-dois
  labels:
    app: flow-dois-secret
    chart: cloudbees-flow
type: Opaque
data:
  CBF_DOIS_ADMIN_PASSWORD: {{ template "dois.cbfAdminPassword" . }}
  CBF_DOIS_PASSWORD:  {{ template "dois.cbfReportUserPassword" . }}
{{- end }}
{{- end }}
