{{- if .Values.dois.backup.externalRepo.enabled -}}
{{- if not .Values.dois.backup.externalRepo.existingSecret }}
{{- if not .Values.dois.backup.externalRepo.serviceAccountsIdentity }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cloudbees-flow.fullname" . }}-dois-backup
  labels:
    app: flow-dois-secret-backup
    chart: cloudbees-flow
type: Opaque
data:
{{- if .Values.dois.backup.externalRepo.secret.awsAccessKey }}
  AWS_ACCESS_KEY:  {{ .Values.dois.backup.externalRepo.secret.awsAccessKey | b64enc }}
{{- end }}
{{- if .Values.dois.backup.externalRepo.secret.awsSecretKey }}
  AWS_SECRET_KEY: {{ .Values.dois.backup.externalRepo.secret.awsSecretKey | b64enc }}
{{- end }}
{{- if .Values.dois.backup.externalRepo.secret.gcsSaKey }}
  GCS_SA_KEY: {{ .Values.dois.backup.externalRepo.secret.gcsSaKey | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
