{{- if .Values.dois.enabled -}}
{{- if not .Values.dois.certificates.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cloudbees-flow.fullname" . }}-dois-certificates
  labels:
    app: flow-dois-secret-certificates
    chart: cloudbees-flow
type: Opaque
data:
{{- if .Values.dois.certificates.ca.crt }}
  CBF_DOIS_CA_CRT: {{ .Values.dois.certificates.ca.crt | b64enc }}
{{- end }}
{{- if .Values.dois.certificates.ca.key }}
  CBF_DOIS_CA_KEY: {{ .Values.dois.certificates.ca.key | b64enc }}
{{- end }}
{{- if .Values.dois.certificates.sign.crt }}
  CBF_DOIS_SIGN_CRT: {{ .Values.dois.certificates.sign.crt | b64enc }}
{{- end }}
{{- if .Values.dois.certificates.sign.key }}
  CBF_DOIS_SIGN_KEY: {{ .Values.dois.certificates.sign.key | b64enc }}
{{- end }}
{{- if .Values.dois.certificates.node.crt }}
  CBF_DOIS_NODE_CRT: {{ .Values.dois.certificates.node.crt | b64enc }}
{{- end }}
{{- if .Values.dois.certificates.node.key }}
  CBF_DOIS_NODE_KEY: {{ .Values.dois.certificates.node.key | b64enc }}
{{- end }}
{{- if .Values.dois.certificates.admin.crt }}
  CBF_DOIS_ADMIN_CRT: {{ .Values.dois.certificates.admin.crt | b64enc }}
{{- end }}
{{- if .Values.dois.certificates.admin.key }}
  CBF_DOIS_ADMIN_KEY: {{ .Values.dois.certificates.admin.key | b64enc }}
{{- end }}
{{- if .Values.dois.certificates.bundle }}
  CBF_DOIS_CRT_BUNDLE: {{ .Values.dois.certificates.bundle | b64enc }}
{{- end }}
{{- end }}
{{- end }}
