{{- if .Values.ingress.enabled -}}
{{- if not .Values.ingress.certificate.existingSecret -}}
{{- if and .Values.ingress.certificate.crt .Values.ingress.certificate.key -}}
apiVersion: v1
kind: Secret
metadata:
  name: flow-tls-secret
  labels:
    app: flow
    chart: {{ .Chart.Name }}
type: Opaque
data:
  tls.crt: {{ .Values.ingress.certificate.crt | b64enc}}
  tls.key: {{ .Values.ingress.certificate.key | b64enc}}
{{- end }}
{{- end }}
{{- end }}
