{{- if .Values.rbac.create -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cbflow-role
  labels:
    app: cbflow-role
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
{{- if .Values.rbac.role.rules }}
{{ toYaml .Values.rbac.role.rules | indent 2 }}
{{- end -}}
{{- end -}}
