{{- if .Values.repository.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: flow-repository
  labels:
    app: flow-repository
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: ef-repository
      port: 8200
      protocol: TCP
      targetPort: p3-repository
  selector:
    app: flow-repository
    release: {{ .Release.Name }}
{{- end }}
