{{- $dbPassword :=  printf "%s" (include "database.dbPassword" .) -}}
{{- if .Values.server.enabled -}}
{{ if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cloudbees-flow.fullname" . }}-db
  labels:
    app: flow-server-db-secret
    chart: cloudbees-flow
type: Opaque
data:
  DB_PASSWORD:  {{ $dbPassword }}
  DB_USER: {{ required ".database.dbUser is required unless .database.existingSecret is specified and set" .Values.database.dbUser | b64enc | quote }}
{{ end }}
{{ end }}
---
{{ if not .Values.flowCredentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cloudbees-flow.fullname" . }}-credentials
  labels:
    app: flow-server-credentials-secret
    role: flow-server-credentials
type: Opaque
data:
  CBF_SERVER_ADMIN_PASSWORD: {{ template "server.cbfServerAdminPassword" . }}
{{ end }}
---
{{ if and .Values.flowLicense .Values.flowLicense.licenseData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cloudbees-flow.fullname" . }}-license
  labels:
    app: flow-server-license-secret
    role: flow-server-credentials
type: Opaque
data:
  CBF_LICENSE: {{ .Values.flowLicense.licenseData | b64enc }}
{{ end }}

---
{{- if .Values.mariadb.enabled }}
{{- if .Values.database.existingSecret }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace .Values.database.existingSecret) }}
{{- if $secret }}
{{- $dbPassword := index $secret.data "DB_PASSWORD" }}
{{- end }}
{{- end }}
# Copied from Mariadb Chart
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-initdb-secret
  labels:
    app: mariadb
    role: mariadb
type: Opaque
data:
  {{- if not (empty .Values.mariadb.rootUser.password) }}
  mariadb-root-password: "{{ .Values.mariadb.rootUser.password | b64enc }}"
  {{ else }}
  mariadb-root-password: {{ template "mariadb.rootPassword" . }}
  {{- end }}
  mariadb-password: "{{ $dbPassword }}"
{{ end }}
---
{{- if .Values.gitops.enabled }}
{{ if not .Values.gitops.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cloudbees-flow.fullname" . }}-gitops
  labels:
    app: gitops-credentials-secret
    role: gitops-credentials
type: Opaque
data:
  CBF_GIT_TOKEN:  {{ .Values.gitops.gitToken | b64enc }}
{{ end }}
{{- end }}