{{- if and .Values.clusteredMode .Values.server.autoscaling.enabled -}}
{{ template "validate.server-hpa" . }}
apiVersion: {{ include "cloudbees-flow-hpa.apiVersion" . }}
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: flow-server-hpa
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: flow-server-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flow-server
  minReplicas: {{ .Values.server.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.server.autoscaling.maxReplicas }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
  metrics:
  {{- with .Values.server.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ . }}
  {{- end }}
  {{- with .Values.server.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource 
    resource: 
      name: memory 
      target:
        type: Utilization
        averageUtilization: {{ . }}
  {{- end }}
  {{- with .Values.server.autoscaling.templates }}
{{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
