{{- if .Values.autoscaling.enabled -}}
{{- if not .Values.gateway.enabled -}}
{{ fail "HPA is not supported for non-gateway agents. autoscaling.enabled can be set to true for agents only when gateway.enabled is also set to true." }}
{{- end -}}
apiVersion: {{ include "cloudbees-flow-agent-hpa.apiVersion" . }}
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: "{{ .Values.releaseNamePrefix | default .Release.Name }}-flow-agent-hpa"
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: "{{ .Values.releaseNamePrefix | default .Release.Name }}-flow-agent-hpa"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: "{{ .Values.releaseNamePrefix | default .Release.Name }}-flow-agent"
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 180
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
  metrics:
  {{- with .Values.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ . }}
  {{- end }}
  {{- with .Values.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource 
    resource: 
      name: memory 
      target:
        type: Utilization
        averageUtilization: {{ . }}
  {{- end }}
  {{- with .Values.autoscaling.templates }}
{{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
