{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cbflowagent-role-{{ .Values.releaseNamePrefix | default .Release.Name }}
  labels:
    app: cbflowagent-role-{{ .Values.releaseNamePrefix | default .Release.Name }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cbflowagent-role-{{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ include "cloudbees-flow-agent.serviceAccountName" . }}
{{- end -}}
