{{ if and ( not .Values.flowCredentials.existingSecret ) ( not .Values.flowCredentials.serverSecretReference )  }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.releaseNamePrefix | default .Release.Name }}-credentials"
  labels:
    app: flow-agent-credentials-secret
    role: flow-agent-credentials
type: Opaque
data:
  CBF_SERVER_USER: {{ required "Either .flowCredentials.existingSecret or .flowCredentials.user must be specified for the Flow user credentials to use to register the agent as a resource with the CloudBees Flow server" .Values.flowCredentials.user | b64enc | quote }}
  CBF_SERVER_PASSWORD: {{ required "Either .flowCredentials.existingSecret or .flowCredentials.password must be specified for the Flow user credentials to use to register the agent as a resource with the CloudBees Flow server" .Values.flowCredentials.password | b64enc | quote }}
{{ end }}
